apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{.Chart.Name}}-data"
  namespace: "{{.Release.Namespace}}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{.Chart.Name}}-init"
  namespace: "{{.Release.Namespace}}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
