apiVersion: v1
kind: Service
metadata:
  name: {{ include "local-kms.fullname" . }}
  labels:
    {{- include "local-kms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "4566"
      port: 4566
      targetPort: 8080
    - name: "4599"
      port: 4599
      targetPort: 8080
  selector:
    {{- include "local-kms.selectorLabels" . | nindent 4 }}
