clusterName: weoss
dns: local
broker:
  storage:
    volumes:
      - id: 0
        type: persistent-claim
        size: 50Gi
        deleteClaim: false
        kraftMetadata: shared
controller:
  storage:
    volumes:
      - id: 0
        type: persistent-claim
        size: 50Gi
        deleteClaim: false
        kraftMetadata: shared
topics:
  - name: test
users:
  - name: sys_costumer
    spec:
      authentication:
        type: scram-sha-512
      authorization:
        acls:
          - resource:
              type: topic
              name: "*"
              patternType: literal
            operations:
              - All
          - resource:
              type: group
              name: "*"
              patternType: literal
            operations:
              - All
