kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "n8n.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.volume.accessMode | default "ReadWriteOnce" | quote }}
  resources:
    requests:
      storage: {{ .Values.volume.size | default "50Gi" | quote }}
  storageClassName: {{ .Values.volume.storageClassName | default "nfs"}}
