{{ $clusterName := .Values.clusterName }}
{{ $namespace := .Release.Namespace }}
{{ $dns := .Values.dns }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: "{{ $clusterName }}"
  namespace: "{{ $namespace }}"
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: "4.0"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    resources:
      limits:
        memory: 1Gi
        cpu: 1
      requests:
        cpu: 200m
        memory: 200Mi
    authorization:
      type: simple
      superUsers:
        - admin
    listeners:
      - name: intplain
        port: 9092
        type: internal
        tls: false
      - name: inttls
        authentication:
          type: tls
        port: 9093
        type: internal
        tls: true
      - name: extscram
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: scram-sha-512
      - name: intscram
        authentication:
          type: scram-sha-512
        port: 9095
        type: internal
        tls: true
        configuration:
          class: nginx
          bootstrap:
            host: kafka.bootstrap.{{$dns}}
          brokers:
          - broker: 0
            host: kafka-0.{{$dns}}
          - broker: 1
            host: kafka-1.{{$dns}}
          - broker: 2
            host: kafka-2.{{$dns}}
    config:
      num.partitions: 3
      default.replication.factor: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 1
      min.insync.replicas: 2
      log.retention.hours: 24
      auto.create.topics.enable: true
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
  entityOperator:
    topicOperator: {}
    userOperator: 
      secretPrefix: user-
