{{ $clusterName := .Values.clusterName }}
{{ $namespace := .Release.Namespace }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-ui
  namespace: "{{ $namespace }}"
  labels:
    strimzi.io/cluster: "{{ $clusterName }}"
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: "topic"
          name: "*"
          patternType: literal
        operations:
          - Describe
          - Read
          - DescribeConfigs
          - ClusterAction
      - resource:
          type: "group"
          name: "*"
          patternType: literal
        operations:
          - Describe
          - Read
          - DescribeConfigs
          - ClusterAction
      - resource:
          type: "cluster"
          name: "*"
          patternType: literal
        operations:
          - Describe
          - Read
          - DescribeConfigs
          - ClusterAction
